# gunakan API versi 1
apiVersion: v1

# tentukan jenis object = Service
kind: Service


metadata:

  name: karsajobs-ui

  labels:
    app: karsajobs
    tier: frontend


spec:

  ports:
  - name: default
    port: 8000
    protocol: TCP
  selector:
    app: karsajobs
    tier: frontend
  type: NodePort