apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui-deployment
spec:
  selector:
    matchLabels:
      app: karsajobs-ui
  replicas: 3
  template:
    metadata:
      labels:
        app: karsajobs-ui
    spec:
      containers:
        - name: karsajobs-ui
          image: mahruz01/karsajobs-ui:latest
          ports:
            - containerPort: 8080
          env:
            - name: VUE_APP_BACKEND
              value: http://<backend-service-ip>:8080
